Controllers/PartnerFormController.cs
using KAUSTConnectForm.HelperClasses;
using KAUSTConnectForm.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.DirectoryServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KAUSTConnectForm.Controllers
{
    public class PartnerFormController : Controller
    {
		Classes Classes = new Classes();
		KCEntities KC = new KCEntities();
		static string HttpLink = ConfigurationManager.ConnectionStrings["Link"].ToString();
		// GET: PartnerForm
		public ActionResult Index()
        {
            return View();
        }

		[HttpGet]
		public ActionResult New()
		{
			return View();
		}

		[HttpPost]
		public ActionResult New(Table_NewRequest table_NewRequest, HttpPostedFileBase image)
		{
			try
			{
				if (image != null)
				{
					table_NewRequest.IDimage = new byte[image.ContentLength];
					image.InputStream.Read(table_NewRequest.IDimage, 0, image.ContentLength);
				}
				if (table_NewRequest.LoginDetailsSentTo == null)
				{
					table_NewRequest.LoginDetailsSentTo = table_NewRequest.ReportingMngEmail;
				}
				var currentUser = System.Web.HttpContext.Current.User.Identity.Name;
				var user = currentUser.Remove(0, 6);
				SearchResult value = Classes.SearchActiveDirectoryByUserName(user);
				var Requester = value.Properties.Contains("displayname") ? Convert.ToString(value.Properties["displayname"][0]) : string.Empty;
				var RequesterEmail = value.Properties.Contains("mail") ? Convert.ToString(value.Properties["mail"][0]) : "no-email";
				table_NewRequest.Requester = Requester;
				table_NewRequest.RequesterEmail = RequesterEmail;
				KC.Table_NewRequest.Add(table_NewRequest);
				KC.SaveChanges();
				int id = table_NewRequest.ID;
				string type = table_NewRequest.NewOrRenew;
				string ReportingManagerUsername = table_NewRequest.ReportingMngUsername;
				string ReportingManagerName = table_NewRequest.ReportingMngName;
				string ReportingManagerEmail = table_NewRequest.ReportingMngEmail;
				TempData["Email"] = table_NewRequest.ReportingMngEmail;
				string FullName = table_NewRequest.FirstName + " " + table_NewRequest.LastName;
				string EncryptedID = Classes.Encrypt(id.ToString());
				string EncryptedReportingManager = Classes.Encrypt(ReportingManagerUsername);
				string ViewLink = String.Format("<a href=\"{0}PartnerForm/ReportingManagerApproval?id={1}&mng={2}\">Click here</a>", HttpLink, EncryptedID, EncryptedReportingManager);
				string StatusLink = String.Format("<a href=\"{0}Home/MySubmissions\">Click here</a>", HttpLink);
				string message = "Dear " + ReportingManagerName +
					",<br /><br /> KAUST Connect Account request has been submitted for <font color='darkblue'> <strong>"
					+ FullName + " </strong></font> by <strong>"
					+ Requester + "</strong>,  please review and approve the request by visit URL below: <br /> <br /> "
					+ ViewLink + "<br /> <br /> Note: Make sure all the details are correct and job title is as per job description. <br /> <br /> Regards, <br /> Messaging Team";
				string RequesterMessage = "Dear " + Requester + ", <br /> <br /> The KAUST Connect Account Request for <strong>" + FullName + "</strong> has been submitted successfully. <br /> <br />To view the status kindly   " + StatusLink + "<br /> <br /> Regards, <br /> Messaging Team";
				if (RequesterEmail != "no-email")
				{
					Classes.SendMail(RequesterEmail, RequesterMessage, FullName, type);
				}
				Classes.SendMail(ReportingManagerEmail, message, FullName, type);
				return RedirectToAction("Submitted", "Form");
			}
			catch
			{
				return RedirectToAction("ErrorOccured", "Home", null);
			}
		}


		[HttpGet]
		public ActionResult Renew()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Renew(Table_NewRequest table_NewRequest, HttpPostedFileBase image)
		{
			try
			{
				if (image != null)
				{
					table_NewRequest.IDimage = new byte[image.ContentLength];
					image.InputStream.Read(table_NewRequest.IDimage, 0, image.ContentLength);
				}
				if (table_NewRequest.LoginDetailsSentTo == null)
				{
					table_NewRequest.LoginDetailsSentTo = table_NewRequest.ReportingMngEmail;
				}
				var currentUser = System.Web.HttpContext.Current.User.Identity.Name;
				var user = currentUser.Remove(0, 6);
				SearchResult value = Classes.SearchActiveDirectoryByUserName(user);
				var Requester = value.Properties.Contains("displayname") ? Convert.ToString(value.Properties["displayname"][0]) : string.Empty;
				var RequesterEmail = value.Properties.Contains("mail") ? Convert.ToString(value.Properties["mail"][0]) : "no-email";
				table_NewRequest.Requester = Requester;
				table_NewRequest.RequesterEmail = RequesterEmail.ToLower();
				KC.Table_NewRequest.Add(table_NewRequest);
				KC.SaveChanges();
				int id = table_NewRequest.ID;
				string type = table_NewRequest.NewOrRenew;
				string ReportingManagerUsername = table_NewRequest.ReportingMngUsername;
				string ReportingManagerName = table_NewRequest.ReportingMngName;
				string ReportingManagerEmail = table_NewRequest.ReportingMngEmail;
				TempData["Email"] = table_NewRequest.ReportingMngEmail;
				string FullName = table_NewRequest.FirstName + " " + table_NewRequest.LastName;
				string EncryptedID = Classes.Encrypt(id.ToString());
				string EncryptedReportingManager = Classes.Encrypt(ReportingManagerUsername);
				string ViewLink = String.Format("<a href=\"{0}PartnerForm/ReportingManagerApproval?id={1}&mng={2}\">Click here</a>", HttpLink, EncryptedID, EncryptedReportingManager);
				string StatusLink = String.Format("<a href=\"{0}Home/MySubmissions\">Click here</a>", HttpLink);
				string message = "Dear " + ReportingManagerName +
					",<br /><br /> KAUST Connect Account request has been submitted for <font color='darkblue'> <strong>"
					+ FullName + " </strong></font> by <strong>"
					+ Requester + "</strong>,  please review and approve the request by visit URL below: <br /> <br /> "
					+ ViewLink + "<br /> <br /> Note: Make sure all the details are correct and job title is as per job description. <br /> <br /> Regards, <br /> Messaging Team";
				Classes.SendMail(ReportingManagerEmail, message, FullName, type);
				string RequesterMessage = "Dear " + Requester + ", <br /> <br /> The KAUST Connect Account Request for <strong>" + FullName + "</strong> has been submitted successfully. <br /> <br />To view the status kindly   " + StatusLink + "<br /> <br /> Regards, <br /> Messaging Team";
				if (RequesterEmail != "no-email")
				{
					Classes.SendMail(RequesterEmail, RequesterMessage, FullName, type);
				}
				return RedirectToAction("Submitted", "Form");
			}
			catch
			{
				return RedirectToAction("ErrorOccured", "Home", null);
			}
		}

		[HttpGet]
		public ActionResult ReportingManagerApproval(string id, string mng)
		{
			string DecryptedManager = Classes.Decrypt(mng);
			string teamMember = System.Web.HttpContext.Current.User.Identity.Name;
			var user = teamMember.Remove(0, 6);
			var approver = Classes.SearchActiveDirectoryForViewStatusApprovers3(user);
			if (approver != null || teamMember.Contains(DecryptedManager))
			{
				string ID = Classes.Decrypt(id);
				int DecryptedID = Convert.ToInt32(ID);
				TempData["ID"] = DecryptedID;
				Table_NewRequest table = KC.Table_NewRequest.Find(DecryptedID);
				TempData["FullName"] = table.FirstName + " " + table.LastName;
				TempData["ManagerEmail"] = table.ManagerEmail;
				TempData["ReportingManager"] = table.ReportingMngName;
				TempData["ManagerName"] = table.ManagerName;
				TempData["Requester"] = table.Requester;
				TempData["RequesterEmail"] = table.RequesterEmail;
				TempData["Manager"] = table.ManagerUsername;
				TempData["Type"] = table.NewOrRenew;
				if (table == null)
				{
					return View();
				}

				var Action = table.StatusOfRequest;
				if (Action != "Pending Reporting Manager Approval")
				{
					ViewBag.Hide = true;
				}
				return View(table);
			}
			else
			{
				return RedirectToAction("AccessDenied", "Home", null);
			}
		}

		[HttpPost]
		public ActionResult ReportingManagerApproval(Table_NewRequest table_NewRequest, string Submit)
		{
			if (Submit == "Reject")
			{
				table_NewRequest.ApprovedBy = System.Web.HttpContext.Current.User.Identity.Name;
				table_NewRequest.ApprovedOn = DateTime.Now.ToString();
				table_NewRequest.StatusOfRequest = "Rejected by Manager";
				table_NewRequest.ID = Convert.ToInt32(TempData["ID"]);
				KC.Entry(table_NewRequest).State = System.Data.Entity.EntityState.Modified;
				KC.SaveChanges();
				string EncryptedID = Classes.Encrypt(table_NewRequest.ID.ToString());
				string FullName = Convert.ToString(TempData["FullName"]);
				string RequesterEmail = Convert.ToString(TempData["RequesterEmail"]);
				string Requester = Convert.ToString(TempData["Requester"]);
				string Type = Convert.ToString(TempData["Type"]);
				string RequesterMessage = "Dear " + Requester + ", <br /> <br /> KAUST Connect Account Request Submitted for <strong>" + FullName + "</strong> has been rejected by your manager. The reason for rejection is <br /> <font color='red'>" + table_NewRequest.Comments + "</font> <br /> <br /> Regards, <br /> Messaging Team";
				Classes.SendMail(RequesterEmail, RequesterMessage, FullName, Type);
				return RedirectToAction("ReportingManagerRejected");
			}
			else
			{
				table_NewRequest.ApprovedBy = System.Web.HttpContext.Current.User.Identity.Name;
				table_NewRequest.ApprovedOn = DateTime.Now.ToString();
				table_NewRequest.StatusOfRequest = "Pending Messaging Team Approval";
				table_NewRequest.ID = Convert.ToInt32(TempData["ID"]);
				KC.Entry(table_NewRequest).State = System.Data.Entity.EntityState.Modified;
				KC.SaveChanges();
				string EncryptedID = Classes.Encrypt(table_NewRequest.ID.ToString());

Views/PartnerForm/ReportingManagerApproval.cshtml
@model KAUSTConnectForm.Models.Table_NewRequest

@{
	ViewBag.Title = "New";
	Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<script>
@*$(document).ready(function () {
		$('#Rejected').click(function () {
			var comments = $('#Comments').val();
			if (comments == "") {
				$('#Comments').attr("class", "form-control is-invalid");
				return false;
			}
			else {
			$.ajax({
				url: "@Url.Action("ReportingManagerRejection", "PartnerForm")",
				data: "Comments=" + comments,
				type: "POST"
				});
			}
	});

	$('#Approved').click(function () {
		var JobTitle = $('#JobTitle').val();
		if (JobTitle == "") {
			$('#JobTitle').attr("class", "form-control is-invalid");
				return false;
			}
			else {
			$.ajax({
				url: "@Url.Action("ReportingManagerApprove", "PartnerForm")",
				data: "Job=" + JobTitle,
				type: "POST"
				});
			}
	});
});*@

	$(document).ready(function () {
		$('form input[type="submit"]').click(function (event) {
			var val = $(this).attr('value');
			var comments = $('#Comments').val();
			if (val == "Reject" || val == "Modify") {
				if (comments == "") {
					$('#Comments').attr("class", "form-control is-invalid");
					return false;
				}
			}
			return true;
		});
	});

	$(document).ready(function () {
		$('#Comments').change(function () {
			$('#Comments').attr("class", "form-control is-valid");
		});
	});

	$(document).on("keydown", "input", function (e) {
		if (e.which == 13) e.preventDefault();
	});

	$(document).ready(function () {
		$('#ShowID').click(function () {
			var imageVal = $('#image').val();
			if (imageVal == "") {
				$('#image').removeAttr("hidden");
				$('#image').val("Close KAUST ID");
				return false;
			}
			else {
				$('#image').attr("hidden", "hidden");
				$('#image').val("");
				return false;
			}
			return false;

		});

	});

</script>

@using (Html.BeginForm("ReportingManagerApproval", "PartnerForm", FormMethod.Post, new { onsubmit = "check(event)" }))
{
	@Html.HiddenFor(x => x.ReportingMngEmail)
	@Html.HiddenFor(x => x.ReportingMngKID)
	@Html.HiddenFor(x => x.ReportingMngName)
	@Html.HiddenFor(x => x.ReportingMngUsername)
	@Html.HiddenFor(x => x.IDimage)
	@Html.HiddenFor(x => x.EmailRequired)
	@Html.HiddenFor(x => x.Email)
	@Html.HiddenFor(x => x.Requester)
	@Html.HiddenFor(x => x.RequesterEmail)
	<div class="container" style="border:1px solid #073642; margin-top: 20px; margin-bottom: 50px; border-radius: 10px;">
		<div class="panel panel-default" style="padding:10px">
			<div class="panel-body">
				<h2>Welcome @Model.ReportingMngName</h2>
				<br />
				<div class="form-group">
					<h4 class="headerClass"><b>REQUEST DETAILS</b></h4>
					<hr />
					<br />
					<div class="row">
						<div class="col-4">
							@Html.LabelFor(model => model.NewOrRenew, "Type")

						</div>
						@{
							if (Model.EmailRequired != "NA")
							{
								<div class="col-4">
									@Html.LabelFor(model => model.EmailRequired, "Email Required")

								</div>
							}

						}
						@{
							if (Model.ExistingUsername != null)
							{
								<div class="col-4">
									@Html.LabelFor(model => model.ExistingUsername, "Existing Username")

								</div>
							}

						}


					</div>
					<div class="row">
						<div class="col-4">
							@Html.TextBoxFor(model => model.NewOrRenew, new { @readonly = "readonly", @class = "form-control" })

						</div>
						@{
							if (Model.EmailRequired != "NA")
							{
								<div class="col-4">
									@Html.TextBoxFor(model => model.EmailRequired, new { @readonly = "readonly", @class = "form-control" })
								</div>
							}

						}
						@{
							if (Model.ExistingUsername != null)
							{
								<div class="col-4">
									@Html.TextBoxFor(model => model.ExistingUsername, new { @readonly = "readonly", @class = "form-control" })

								</div>
							}
						}
					</div>
				</div>
				<div class="form-group">
					<h4 class="headerClass"><b>USER DETAILS</b></h4>
					<hr />

					<div class="row">
						<div class="col-4">
							@Html.LabelFor(model => model.FirstName, "First Name")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.MiddleName, "Middle Initial")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.LastName, "Last Name")
						</div>
					</div>
					<div class="row">
						<div class="col-4">
							@Html.TextBoxFor(model => model.FirstName, new { @readonly = "readonly", @class = "form-control" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.MiddleName, new { @readonly = "readonly", @class = "form-control" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.LastName, new { @readonly = "readonly", @class = "form-control" })
						</div>
					</div>
					<br />
					<div class="row">
						<div class="col-4">
							@Html.LabelFor(model => model.KAUSTID, "KAUST ID")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.JobTitle, "Job Title")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.VendorName, "Partner Name")
						</div>
					</div>
					<div class="row">
						<div class="col-4">
							@Html.TextBoxFor(model => model.KAUSTID, new { @readonly = "readonly", @class = "form-control" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.JobTitle, new { @class = "form-control" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.VendorName, new { @readonly = "readonly", @class = "form-control" })
						</div>
					</div>
					<br />
					<label style="color:red">*Please verify/correct the job title as per job description, if required</label>
					<br />
					@{
						if (Model.UserComments != null)
						{
							<div class="row">
								<div class="col-12">
									@Html.LabelFor(model => model.UserComments, "Comments")
								</div>
							</div>
							<div class="row">
								<div class="col-12">
									@Html.TextBoxFor(model => model.UserComments, new { @readonly = "readonly", @class = "form-control" })
								</div>
							</div>
						}

					}
				</div>
				<br />
				<div class="form-group">
					<h4 class="headerClass"><b>KAUST DEPARTMENT MANAGER</b></h4>
					<hr />
					<div class="row">
						<div class="col-4">
							@Html.LabelFor(model => model.ManagerUsername, "Manager Username")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.ManagerName, "Manager Name")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.ManagerTitle, "Manager Title")
						</div>
					</div>
					<div class="row">
						<div class="col-4">
							@Html.TextBoxFor(model => model.ManagerUsername, new { @class = "form-control", @readonly = "readonly" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.ManagerName, new { @class = "form-control", @readonly = "readonly" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.ManagerTitle, new { @class = "form-control", @readonly = "readonly" })
						</div>
					</div>
					<br />
					<div class="row">
						<div class="col-4">
							@Html.LabelFor(model => model.ManagerDept, "Department")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.ManagerEmail, "Email")
						</div>
						<div class="col-4">
							@Html.LabelFor(model => model.ManagerKID, "KAUST ID")
						</div>

					</div>
					<div class="row">
						<div class="col-4">
							@Html.TextBoxFor(model => model.ManagerDept, new { @class = "form-control", @readonly = "readonly" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.ManagerEmail, new { @class = "form-control", @readonly = "readonly" })
						</div>
						<div class="col-4">
							@Html.TextBoxFor(model => model.ManagerKID, new { @class = "form-control", @readonly = "readonly" })
						</div>
					</div>
				</div>

				<div class="form-group" style="text-align:center">
					<div class="row">
						<div class="col-4">
						</div>
						<div class="col-4">
							<input type="submit" name="ShowID" id="ShowID" value="View KAUST ID" class="btn btn-info" />
							<br />
							<br />
							<img src='data:image/jpeg;base64,@(Convert.ToBase64String(Model.IDimage))' id="image" height="300" width="200" hidden />

						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-4">
					</div>
					<div class="col-4">
						<div style="text-align:center">
							@Html.Label("Comments")
							@Html.TextAreaFor(m => m.Comments, 5, 10, new { @class = "form-control", @id = "Comments" })
						</div>
					</div>
				</div>
				@{
					bool value = Convert.ToBoolean(ViewBag.Hide);
					if (value == false)
					{

						<br />
						<div style="text-align: center">
							<input type="submit" value="Approve" id="Approve" class="btn btn-success" name="Submit" /> <input type="submit" id="Reject" value="Reject" class="btn btn-danger" name="Submit" />
						</div>
						@*<div style="text-align: center;">
								<br />
								@Html.ActionLink("Approved", "ReportingManagerApproved", "Home", new { @class = "btn btn-success", @id = "Approved" })
								@Html.ActionLink("Rejected", "ReportingManagerRejected", "Home", new { @class = "btn btn-danger", @id = "Rejected" })
								<br />
							</div>*@
					}
				}

			</div>
			<br />
		</div>
	</div>
}

Views/PartnerForm/ReportingManagerApproved.cshtml

@{
    ViewBag.Title = "ReportingManagerApproved";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<script type="text/javascript">
$(document).ready(function () {
    history.pushState({ page: 1 }, "title 1", "#");
    window.onhashchange = function (event) {
        window.location.hash = "no-going-back";
    };
	});
</script>
<div class="container" style=" margin-top: 20px; margin-bottom: 50px; border-radius: 10px;">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="alert alert-dismissible alert-success" style="font-size:medium">
				<center><strong>Thank you.</strong> Email has been sent to the Authorised Manager for further approval!</center>
				<br />
				<center>NOTE: Kindly close this tab and avoid clicking the back button</center>

			</div>
		</div>
	</div>
</div>


Views/PartnerForm/ReportingManagerRejected.cshtml

@{
	ViewBag.Title = "ReportingManagerRejected";
	Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<script type="text/javascript">
$(document).ready(function () {
    history.pushState({ page: 1 }, "title 1", "#");
    window.onhashchange = function (event) {
        window.location.hash = "no-going-back";
    };
	});
</script>
<div class="container" style=" margin-top: 20px; margin-bottom: 50px; border-radius: 10px;">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="alert alert-dismissible alert-danger" style="font-size:medium">
				<center>Request has been rejected</center>
				<br />
				<center>NOTE: Kindly close this tab and avoid clicking the back button</center>
			</div>

		</div>
	</div>
</div>

